# Generated by Django 5.1 on 2024-08-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('button_1_text', models.CharField(max_length=25)),
                ('button_1_link', models.CharField(max_length=255)),
                ('button_2_text', models.CharField(max_length=25)),
                ('button_2_link', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/banner/')),
            ],
        ),
    ]
