# Generated by Django 5.1 on 2024-08-19 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=20)),
                ('heading', models.CharField(help_text='&lt;span class="title-highlight"&gt;Services&lt;/span&gt; We Can Help You With !', max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(help_text='&lt;span class="title-highlight"&gt;Digital&lt;/span&gt; Agency You Can Rely Upon !', max_length=255),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('service_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.servicesection')),
            ],
        ),
    ]
