# Generated by Django 5.1 on 2024-08-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_servicesection_alter_banner_heading_servicefeature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='servicesection',
            options={'verbose_name': 'Service Section', 'verbose_name_plural': 'Service Section'},
        ),
        migrations.AddField(
            model_name='banner',
            name='highlight_heading',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='heading',
            field=models.CharField(max_length=255),
        ),
    ]
