# Generated by Django 5.1 on 2024-08-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_banner_options_alter_servicesection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=15)),
                ('highlight_heading', models.CharField(max_length=15)),
                ('heading', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('video', models.CharField(help_text='Just copy video id from youtube url i.e. <strong>IUN664s7N-c</strong>', max_length=100)),
                ('thumbnail', models.ImageField(upload_to='images/about/')),
                ('image_1', models.ImageField(upload_to='images/about/')),
                ('image_2', models.ImageField(upload_to='images/about/')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
