# Generated by Django 5.1 on 2024-08-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_aboutfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
