# Generated by Django 5.1 on 2024-08-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_aboutsection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
