# Generated by Django 5.1 on 2024-08-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_aboutsection_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='year',
            field=models.IntegerField(),
        ),
    ]
