# Generated by Django 5.1 on 2024-08-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_goalsection_goalcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcounter',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
