# Generated by Django 5.1 on 2024-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_portfoliosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=15)),
                ('highlight_heading', models.CharField(max_length=15)),
                ('heading', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Testimonial Section',
                'verbose_name_plural': 'Testimonial Section',
            },
        ),
    ]
