# Generated by Django 5.1 on 2024-08-28 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_portfolioimage_portfoliotechnology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degisnation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/team/')),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.degisnation')),
            ],
        ),
    ]
