# Generated by Django 5.1 on 2024-08-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_technology_teammember_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='technologies',
            field=models.ManyToManyField(to='portfolio.technology'),
        ),
        migrations.DeleteModel(
            name='PortfolioTechnology',
        ),
    ]
