# Generated by Django 5.1 on 2024-08-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_experience_qualification_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
