# Generated by Django 5.1 on 2024-08-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_teammember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='short_description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
