# Generated by Django 5.1 on 2024-08-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_teammember_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
