# Generated by Django 5.1 on 2024-09-01 06:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolioimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
