# Generated by Django 5.1 on 2024-09-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='short_description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
