# Generated by Django 5.1 on 2024-09-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_portfolio_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='images/client/')),
                ('rating', models.FloatField()),
            ],
        ),
    ]
