# Generated by Django 5.1 on 2024-09-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.FloatField(help_text='1 to 5 i.e. 4/4.5/5'),
        ),
    ]
